site_name: "Curse of Strahd: Master Quest"
site_author: Colin Woodbury
repo_url: https://gitlab.com/fosskers/curse-of-strahd
docs_dir: cos
theme: readthedocs

pages:
- Home: index.md
- The Hook: hook.md
- Endings: endings.md
- Travel: travel.md
- Rolls and Charts: rolls.md
- Magic Items: magic-items.md
- Renown: renown.md
- Key Characters:
    - Strahd von Zarovich: strahd.md
    - "Ezmerelda d'Avenir": ezmerelda.md
    - Ireena Kolyana: ireena.md
- Locations:
    - Death House: death-house.md
    - Village of Barovia: barovia-village.md
    - Tser Pool Encampment: tser-pool.md
    - Old Bonegrinder: bonegrinder.md
    - Vallaki: vallaki.md
    - Krezk: krezk.md
    - Wizard of Wines: winery.md
    - "Van Richten's Tower": van-richten-tower.md
    - Yester Hill: yesterhill.md
    - Argynvostholt: argynvostholt.md
    - Ruins of Berez: berez.md
    - Amber Temple: amber-temple.md
    - Castle Ravenloft: ravenloft.md
- Appendix:
    - Vampires: vampires.md
    - Text Errata: errata.md
    - On the Tarokka Deck: tarokka.md
    - Cutting the Werewolf Den: werewolves.md
    - Speed Running: speedrun.md
    - Trivia: trivia.md

markdown_extensions:
- toc:
    permalink: true
